/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verifica a disponibilidade da API e do banco */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retorna os indicadores operacionais */
        get: operations["getDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assignees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista os responsáveis */
        get: operations["listAssignees"];
        put?: never;
        /** Adiciona um membro à equipe */
        post: operations["createAssignee"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assignees/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        get?: never;
        /** Atualiza um membro da equipe */
        put: operations["updateAssignee"];
        post?: never;
        /** Remove um membro sem chamados associados */
        delete: operations["deleteAssignee"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista e filtra chamados */
        get: operations["listTickets"];
        put?: never;
        /** Cria um chamado */
        post: operations["createTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tickets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TicketID"];
            };
            cookie?: never;
        };
        /** Retorna os detalhes de um chamado */
        get: operations["getTicket"];
        /** Atualiza um chamado */
        put: operations["updateTicket"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tickets/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TicketID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Altera diretamente o status de um chamado */
        patch: operations["changeTicketStatus"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Priority: "low" | "medium" | "high";
        /** @enum {string} */
        TicketStatus: "open" | "in_progress" | "resolved" | "closed";
        /** @enum {string} */
        AssignmentMode: "manual" | "automatic";
        /** @enum {string} */
        TicketSort: "priority_desc" | "opened_desc" | "opened_asc" | "updated_desc";
        Ticket: {
            /** Format: int64 */
            id: number;
            title: string;
            description: string;
            requesterName: string;
            priority: components["schemas"]["Priority"];
            status: components["schemas"]["TicketStatus"];
            /** Format: int64 */
            assigneeId: number;
            assigneeName: string;
            assignmentMode: components["schemas"]["AssignmentMode"];
            /** Format: date-time */
            openedAt: string;
            /** Format: date-time */
            resolvedAt: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        TicketInput: {
            title: string;
            description: string;
            requesterName: string;
            priority: components["schemas"]["Priority"];
            status: components["schemas"]["TicketStatus"];
            assignmentMode: components["schemas"]["AssignmentMode"];
            /** Format: int64 */
            assigneeId: number;
            redistribute: boolean;
        };
        StatusInput: {
            status: components["schemas"]["TicketStatus"];
        };
        Assignee: {
            /** Format: int64 */
            id: number;
            name: string;
            active: boolean;
            openTickets: number;
            completedTickets: number;
            /** Format: date-time */
            lastAssignedAt: string | null;
        };
        AssigneeInput: {
            name: string;
        };
        Dashboard: {
            total: number;
            open: number;
            inProgress: number;
            resolved: number;
            closed: number;
            assignees: components["schemas"]["Assignee"][];
            nextAssignee: components["schemas"]["Assignee"] | null;
        };
        ApiError: {
            code: string;
            message: string;
            fields?: {
                [key: string]: string;
            };
        };
        Health: {
            status: string;
            database: string;
        };
    };
    responses: {
        /** @description Requisição inválida */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Chamado não encontrado */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Dados inválidos */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description A operação conflita com o estado atual */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Erro interno */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
    };
    parameters: {
        TicketID: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Aplicação disponível */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Banco de dados indisponível */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Indicadores carregados */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dashboard"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    listAssignees: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Responsáveis disponíveis */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assignee"][];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    createAssignee: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssigneeInput"];
            };
        };
        responses: {
            /** @description Membro criado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assignee"];
                };
            };
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    updateAssignee: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssigneeInput"];
            };
        };
        responses: {
            /** @description Membro atualizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assignee"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    deleteAssignee: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Membro removido */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listTickets: {
        parameters: {
            query?: {
                search?: string;
                status?: components["schemas"]["TicketStatus"];
                priority?: components["schemas"]["Priority"];
                assigneeId?: number;
                sort?: components["schemas"]["TicketSort"];
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chamados encontrados */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticket"][];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    createTicket: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TicketInput"];
            };
        };
        responses: {
            /** @description Chamado criado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticket"];
                };
            };
            422: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
        };
    };
    getTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TicketID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chamado encontrado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticket"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    updateTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TicketID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TicketInput"];
            };
        };
        responses: {
            /** @description Chamado atualizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticket"];
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
        };
    };
    changeTicketStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TicketID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusInput"];
            };
        };
        responses: {
            /** @description Status atualizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticket"];
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
        };
    };
}
